/**
 * Host pattern matching. Supports:
 *   - exact + parent-domain match:  `github.com` matches `github.com`,
 *     `www.github.com`, `api.staging.github.com`
 *   - leading wildcard subdomain:    `*.example.com` matches any
 *     direct subdomain but not `example.com` itself (matches FoxyProxy
 *     and SwitchyOmega semantics)
 *   - bare `*` matches any host
 *   - IPv4 CIDR:                    `192.168.0.0/16` matches any IPv4 in range
 *   - IPv6 CIDR:                    `fe80::/10` matches any IPv6 in range
 *
 * Not supported (by design — keeps the mental model simple):
 *   - TLD wildcards like `example.*`
 *   - Glob `?` and `[abc]`
 *   - Mixed: `*.lan` is fine; `api.*.lan` is not
 *
 * The same matcher drives rules, exclusions, and the Chrome PAC script.
 * The Firefox listener uses the typed version directly; the PAC script
 * is generated by inlining the same algorithm into JS in chrome.ts.
 */

export function patternMatches(host: string, pattern: string): boolean {
  const h = (host || '').toLowerCase().replace(/\.+$/, '');
  const p = (pattern || '').toLowerCase().replace(/\.+$/, '');
  if (!h || !p) return false;

  // CIDR (IPv4 or IPv6)
  if (p.includes('/')) {
    if (isIpv4(h)) return cidrContainsIpv4(inetAton4(h), parseIpv4Cidr(p));
    if (isIpv6(h)) return cidrContainsIpv6(inetAton6(h), parseIpv6Cidr(p));
    return false;
  }

  // Wildcard
  if (p.includes('*')) {
    return wildcardToRegex(p).test(h);
  }

  // Exact + parent-domain
  return h === p || h.endsWith(`.${p}`);
}

function wildcardToRegex(pattern: string): RegExp {
  // Bare `*` matches anything (including dots).
  if (pattern === '*') return /^.*$/;
  // Otherwise `*` matches one or more chars (excluding dots, so it
  // doesn't accidentally swallow subdomains). Anchored.
  const escaped = pattern.replace(/[.+?^${}()|[\]\\]/g, '\\$&').replace(/\*/g, '[^.]+');
  return new RegExp(`^${escaped}$`);
}

// --- IPv4 ---

function isIpv4(s: string): boolean {
  return /^\d{1,3}(\.\d{1,3}){3}$/.test(s);
}

function inetAton4(s: string): number | null {
  const parts = s.split('.').map((n) => Number(n));
  if (parts.length !== 4 || parts.some((n) => !Number.isInteger(n) || n < 0 || n > 255)) return null;
  return ((parts[0]! << 24) | (parts[1]! << 16) | (parts[2]! << 8) | parts[3]!) >>> 0;
}

function parseIpv4Cidr(s: string): { base: number; bits: number } | null {
  const [ip, prefixStr] = s.split('/');
  const prefix = Number(prefixStr);
  if (!ip || !Number.isInteger(prefix) || prefix < 0 || prefix > 32) return null;
  const base = inetAton4(ip);
  if (base === null) return null;
  return { base, bits: prefix };
}

function cidrContainsIpv4(host: number | null, cidr: { base: number; bits: number } | null): boolean {
  if (host === null || cidr === null) return false;
  if (cidr.bits === 0) return true;
  const mask = cidr.bits === 32 ? 0xffffffff : (~((1 << (32 - cidr.bits)) - 1)) >>> 0;
  return (host & mask) === (cidr.base & mask);
}

// --- IPv6 ---

function isIpv6(s: string): boolean {
  return s.includes(':');
}

const IPV6_SEGMENTS = 8n;

function inetAton6(s: string): bigint | null {
  // Accept `::` shorthand and fully-expanded forms.
  try {
    if (s.includes(':::')) return null;
    let parts: string[];
    if (s.includes('::')) {
      const [head = '', tail = ''] = s.split('::');
      const headParts = head === '' ? [] : head.split(':');
      const tailParts = tail === '' ? [] : tail.split(':');
      const missing = Number(IPV6_SEGMENTS) - headParts.length - tailParts.length;
      if (missing < 0) return null;
      parts = [...headParts, ...Array(missing).fill('0'), ...tailParts];
    } else {
      parts = s.split(':');
    }
    if (parts.length !== 8) return null;
    let result = 0n;
    for (const seg of parts) {
      if (!/^[0-9a-fA-F]{1,4}$/.test(seg)) return null;
      result = (result << 16n) | BigInt(parseInt(seg, 16));
    }
    return result;
  } catch {
    return null;
  }
}

function parseIpv6Cidr(s: string): { base: bigint; bits: number } | null {
  const [ip, prefixStr] = s.split('/');
  const prefix = Number(prefixStr);
  if (!ip || !Number.isInteger(prefix) || prefix < 0 || prefix > 128) return null;
  const base = inetAton6(ip);
  if (base === null) return null;
  return { base, bits: prefix };
}

function cidrContainsIpv6(host: bigint | null, cidr: { base: bigint; bits: number } | null): boolean {
  if (host === null || cidr === null) return false;
  if (cidr.bits === 0) return true;
  const mask = cidr.bits === 128 ? (1n << 128n) - 1n : ((1n << BigInt(128 - cidr.bits)) - 1n) ^ ((1n << 128n) - 1n);
  return (host & mask) === (cidr.base & mask);
}
